version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: lbs_elastic
    environment:
      - node.name=es01
      - cluster.name=lbs-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=${ES_MEM_OPTS}"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - lbs-net

  kibana:
    image: kibana:8.11.1
    container_name: lbs_kibana
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - lbs-net

volumes:
  es_data:
    driver: local

networks:
  lbs-net:
    driver: bridge
